### ISSUE TITLE
Peer-to-Peer review session

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/Mint.com-Clone-Daniel-Kyle#3]
Please leave some comments :)

**Comment by nyatindopatrick** [comment]
The code super is clean though I thought you should fix these:
- Phone number input field has a name "email" 
- password type should be "password", not "text"
- The footer links should be wrapped in <a> tags since they are "links"

**Comment by patriciachrysy** [comment]
On the phone form field, the type of the input should be 'tel' instead of number. Also, there is an hidden form input named 'Password confirmation' that needs to be there.
When you are using inputs outside the label tags, it is best practice to add a 'for' attribute to your label with the value of an id on the input field as it's own value too. 
It will be good to add more control on your input like:
- adding a maxlength on the password field
- adding a pattern to force user to choose a complicated password
- adding a pattern to the email to force to put a correct email address
You also forgot to add the fixed floating button on the bottom right of your page

**Comment by Kyle-Law** [comment]
Thanks @patriciachrysy and @nyatindopatrick ! Your insightful suggestions have been implemented :)
